/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jacek' at '11/8/14 2:35 PM' with Gradle 2.1
 *
 * @author jacek, @date 11/8/14 2:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
